'use strict';

/**
* @ngdoc service
* @name betterCalcApp.controls
* @description
* # controls
* Service in the betterCalcApp.
*/
angular.module('betterCalcApp')
.service('controls', function() {
    return {
        data: {
            scientifics: [{
                label: '-',
                value: '',
                enable: true
            }, {
                label: '-',
                value: '',
                enable: true
            }, {
                label: '-',
                value: '',
                enable: true
            }, {
                label: 'Inv',
                value: '',
                enable: true
            }, {
                label: 'sin',
                value: '',
                enable: true
            }, {
                label: 'In',
                value: '',
                enable: true
            }, {
                label: 'π',
                value: '',
                enable: true
            }, {
                label: 'cos',
                value: '',
                enable: true
            }, {
                label: 'log',
                value: '',
                enable: true
            }, {
                label: 'e',
                value: '',
                enable: true
            }, {
                label: 'tan',
                value: '',
                enable: true
            }, {
                label: '√',
                value: '',
                enable: true
            }, {
                label: 'Ans',
                value: '',
                enable: true
            }, {
                label: 'Exp',
                value: '',
                enable: true
            }, {
                label: 'xy',
                value: '',
                enable: true
            }],
            digits: [{
                label: '(',
                value: '(',
                enable: false
            }, {
                label: ')',
                value: ')',
                enable: false
            }, {
                label: '%',
                value: '%',
                enable: false
            }, {
                label: '9',
                value: '9',
                enable: true
            }, {
                label: '8',
                value: '8',
                enable: true
            }, {
                label: '7',
                value: '7',
                enable: true
            }, {
                label: '6',
                value: '6',
                enable: true
            }, {
                label: '5',
                value: '5',
                enable: true
            }, {
                label: '4',
                value: '4',
                enable: true
            }, {
                label: '3',
                value: '3',
                enable: true
            }, {
                label: '2',
                value: '2',
                enable: true
            }, {
                label: '1',
                value: '1',
                enable: true
            }, {
                label: '0',
                value: '0',
                enable: true
            }, {
                label: '.',
                value: '.',
                enable: true
            }, {
                label: '=',
                value: '=',
                enable: true,
                type: 'calculator'
            }],
            operators: [{
                label: 'AC',
                action: 'clear',
                enable: true,
                value: '',
                type: 'clear'
            }, {
                label: '÷',
                action: 'divide',
                enable: true,
                value: '÷'
            }, {
                label: 'x',
                action: 'multiply',
                enable: true,
                value: 'x'
            }, {
                label: '-',
                action: 'subtract',
                enable: true,
                value: '-'
            }, {
                label: '+',
                action: 'addition',
                enable: true,
                value: '+'
            }]
        }
    }
});
